openapi: 3.0.1
info:
  title: '@jupiterone/graph-godaddy'
  description: A graph conversion tool for https://developer.godaddy.com/
  x-cortex-git:
    github:
      repository: JupiterOne/graph-godaddy
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-godaddy'
  x-cortex-service-groups:
    - tier-4
